version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
      - ./backend:/app
      - /app/node_modules
      - ./backend/databases:/app/databases # Persistent volume for NeDB database files
